---
name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - uses: extractions/setup-just@v2
      - name: Check formatting, linting and import sorting
        run: just check
